import type { PeriodKind } from "./clock";
import type { CounterKey, NeedKey } from "./types";

export type ActivityEffects = Partial<Record<NeedKey, number>> & { grades?: number; xp?: number };

/** A part-time job pays when the shift is finished. */
export type JobDef = {
  basePay: number;
  /** Where on the map the job is, for the wallet's "ways to earn" list. */
  where: string;
  /** Extra pay for each classmate at school (customers), up to `maxExtra`. */
  perClassmate?: number;
  maxExtra?: number;
};

export type ActivityDef = {
  key: string;
  label: string;
  /** Shown in a bubble over the student while they do it. */
  emoji: string;
  verb: string;
  durationSec: number;
  /** Price in Naira, paid when the activity starts. */
  cost: number;
  effects: ActivityEffects;
  /** When set, the activity only works during these periods. */
  periods?: PeriodKind[];
  closedMessage?: string;
  counter?: CounterKey;
  job?: JobDef;
  /** Opens a screen (games table, shop, bank) instead of running a timed activity. */
  opens?: "games" | "shop" | "bank";
};

export const activities: Record<string, ActivityDef> = {
  assembly: {
    key: "assembly",
    label: "Join assembly",
    emoji: "🎤",
    verb: "at assembly",
    durationSec: 10,
    cost: 0,
    effects: { social: 8, xp: 10 },
    periods: ["assembly"],
    closedMessage: "Assembly is in the morning.",
    counter: "assembly",
  },
  attend_lesson: {
    key: "attend_lesson",
    label: "Attend lesson",
    emoji: "📝",
    verb: "in class",
    durationSec: 20,
    cost: 0,
    effects: { grades: 12, energy: -6, fun: -3, xp: 15 },
    periods: ["lesson"],
    closedMessage: "No lesson right now — study in the library instead.",
    counter: "lessons",
  },
  study: {
    key: "study",
    label: "Study",
    emoji: "📚",
    verb: "studying",
    durationSec: 15,
    cost: 0,
    effects: { grades: 8, energy: -6, fun: -4, xp: 8 },
    periods: ["assembly", "lesson", "break", "after"],
    closedMessage: "The library is closed. Go home and rest!",
    counter: "study",
  },
  read_comics: {
    key: "read_comics",
    label: "Read comics",
    emoji: "📖",
    verb: "reading",
    durationSec: 10,
    cost: 0,
    effects: { fun: 14, energy: -2 },
    periods: ["assembly", "lesson", "break", "after"],
    closedMessage: "The library is closed.",
  },
  buy_meal: {
    key: "buy_meal",
    label: "Buy jollof rice",
    emoji: "🍛",
    verb: "eating",
    durationSec: 6,
    cost: 500,
    effects: { hunger: 45, fun: 3 },
    periods: ["break", "after"],
    closedMessage: "The canteen opens at break time.",
    counter: "meals",
  },
  buy_snack: {
    key: "buy_snack",
    label: "Buy puff-puff",
    emoji: "🍩",
    verb: "snacking",
    durationSec: 4,
    cost: 200,
    effects: { hunger: 18, fun: 4 },
    periods: ["break", "after"],
    closedMessage: "The canteen opens at break time.",
    counter: "snacks",
  },
  drink_water: {
    key: "drink_water",
    label: "Drink water",
    emoji: "🚰",
    verb: "drinking",
    durationSec: 3,
    cost: 0,
    effects: { hunger: 5, energy: 2 },
  },
  play_football: {
    key: "play_football",
    label: "Play football",
    emoji: "⚽",
    verb: "playing football",
    durationSec: 15,
    cost: 0,
    effects: { fun: 20, energy: -12, social: 4, xp: 6 },
    periods: ["break", "after"],
    closedMessage: "Football is for break time and after school.",
    counter: "football",
  },
  rest: {
    key: "rest",
    label: "Rest",
    emoji: "😴",
    verb: "resting",
    durationSec: 12,
    cost: 0,
    effects: { energy: 30 },
    counter: "rest",
  },
  board_games: {
    key: "board_games",
    label: "Play table games",
    emoji: "🎲",
    verb: "playing a table game",
    durationSec: 0,
    cost: 0,
    effects: {},
    periods: ["assembly", "lesson", "break", "after"],
    closedMessage: "The Common Room is closed. See you tomorrow!",
    opens: "games",
  },
  // Part-time jobs: a way to earn money outside lessons. Only a few shifts a day.
  canteen_job: {
    key: "canteen_job",
    label: "Help at the canteen",
    emoji: "🧑‍🍳",
    verb: "serving food",
    durationSec: 15,
    cost: 0,
    effects: { energy: -10, hunger: 10, xp: 5 },
    periods: ["break", "after"],
    closedMessage: "The canteen needs helpers at break and after school.",
    counter: "shifts",
    job: { basePay: 400, where: "Canteen kitchen" },
  },
  library_job: {
    key: "library_job",
    label: "Shelve library books",
    emoji: "📦",
    verb: "shelving books",
    durationSec: 12,
    cost: 0,
    effects: { energy: -6, fun: -4, xp: 5 },
    periods: ["assembly", "break", "after"],
    closedMessage: "The librarian needs help outside lesson time.",
    counter: "shifts",
    job: { basePay: 250, where: "Library, by the bookshelf" },
  },
  sweep_job: {
    key: "sweep_job",
    label: "Sweep the classroom",
    emoji: "🧹",
    verb: "sweeping",
    durationSec: 12,
    cost: 0,
    effects: { energy: -10, fun: -5, xp: 4 },
    periods: ["after"],
    closedMessage: "Classroom cleaning is after school.",
    counter: "shifts",
    job: { basePay: 300, where: "Classroom A, back corner" },
  },
  snack_stall: {
    key: "snack_stall",
    label: "Sell chin-chin",
    emoji: "🛍️",
    verb: "selling chin-chin",
    durationSec: 15,
    cost: 0,
    effects: { energy: -6, social: 6, xp: 6 },
    periods: ["break", "after"],
    closedMessage: "The snack stall opens at break time.",
    counter: "shifts",
    // More classmates at school means more customers.
    job: { basePay: 200, perClassmate: 100, maxExtra: 500, where: "Main Corridor, east end" },
  },
  // The rest of the school.
  water_crops: {
    key: "water_crops",
    label: "Water the crops",
    emoji: "🪣",
    verb: "watering crops",
    durationSec: 12,
    cost: 0,
    effects: { energy: -10, fun: -2, xp: 4 },
    periods: ["break", "after"],
    closedMessage: "The farm needs helpers at break and after school.",
    counter: "shifts",
    job: { basePay: 300, where: "School Farm" },
  },
  pick_oranges: {
    key: "pick_oranges",
    label: "Pick oranges",
    emoji: "🍊",
    verb: "eating oranges",
    durationSec: 6,
    cost: 0,
    effects: { hunger: 15, fun: 3 },
    periods: ["break", "after"],
    closedMessage: "You can pick oranges at break and after school.",
  },
  watch_match: {
    key: "watch_match",
    label: "Cheer from the stands",
    emoji: "📣",
    verb: "cheering",
    durationSec: 10,
    cost: 0,
    effects: { fun: 10, social: 5 },
    periods: ["break", "after"],
    closedMessage: "Matches are at break and after school.",
  },
  play_basketball: {
    key: "play_basketball",
    label: "Play basketball",
    emoji: "🏀",
    verb: "playing basketball",
    durationSec: 12,
    cost: 0,
    effects: { fun: 18, energy: -12, social: 4, xp: 5 },
    periods: ["break", "after"],
    closedMessage: "Basketball is for break time and after school.",
  },
  do_experiment: {
    key: "do_experiment",
    label: "Do an experiment",
    emoji: "🧪",
    verb: "doing an experiment",
    durationSec: 15,
    cost: 0,
    effects: { grades: 10, fun: 5, energy: -4, xp: 8 },
    periods: ["lesson", "after"],
    closedMessage: "The lab is open in lesson time and after school.",
    counter: "study",
  },
  practise_coding: {
    key: "practise_coding",
    label: "Practise coding",
    emoji: "💻",
    verb: "coding",
    durationSec: 15,
    cost: 0,
    effects: { grades: 8, fun: 6, energy: -4, xp: 8 },
    periods: ["assembly", "lesson", "break", "after"],
    closedMessage: "The computer lab is closed.",
    counter: "study",
  },
  fix_computers: {
    key: "fix_computers",
    label: "Fix the computers",
    emoji: "🛠️",
    verb: "fixing computers",
    durationSec: 14,
    cost: 0,
    effects: { energy: -8, fun: 2, xp: 6 },
    periods: ["break", "after"],
    closedMessage: "The computer lab needs help at break and after school.",
    counter: "shifts",
    job: { basePay: 350, where: "Computer Lab" },
  },
  play_drums: {
    key: "play_drums",
    label: "Play the drums",
    emoji: "🥁",
    verb: "drumming",
    durationSec: 10,
    cost: 0,
    effects: { fun: 16, social: 3, energy: -4 },
    periods: ["break", "after"],
    closedMessage: "The music room is open at break and after school.",
  },
  paint: {
    key: "paint",
    label: "Paint a picture",
    emoji: "🎨",
    verb: "painting",
    durationSec: 12,
    cost: 0,
    effects: { fun: 14, energy: -2, xp: 3 },
    periods: ["break", "after"],
    closedMessage: "The art room is open at break and after school.",
  },
  watch_tv: {
    key: "watch_tv",
    label: "Watch TV",
    emoji: "📺",
    verb: "watching TV",
    durationSec: 12,
    cost: 0,
    effects: { fun: 14, energy: 4 },
    periods: ["break", "after"],
    closedMessage: "The TV is on at break and after school.",
  },
  listen_music: {
    key: "listen_music",
    label: "Listen to music",
    emoji: "🎧",
    verb: "listening to music",
    durationSec: 8,
    cost: 0,
    effects: { fun: 10, social: 2 },
    periods: ["break", "after"],
    closedMessage: "The music corner is open at break and after school.",
  },
  rest_sickbay: {
    key: "rest_sickbay",
    label: "Lie down in the sick bay",
    emoji: "🛏️",
    verb: "resting in the sick bay",
    durationSec: 18,
    cost: 0,
    effects: { energy: 45 },
    counter: "rest",
  },
  school_shop: {
    key: "school_shop",
    label: "Shop for clothes",
    emoji: "🛍️",
    verb: "shopping",
    durationSec: 0,
    cost: 0,
    effects: {},
    periods: ["assembly", "lesson", "break", "after"],
    closedMessage: "The shop is closed. Come back tomorrow!",
    opens: "shop",
  },
  school_bank: {
    key: "school_bank",
    label: "Use the School Bank",
    emoji: "🏦",
    verb: "at the bank",
    durationSec: 0,
    cost: 0,
    effects: {},
    periods: ["assembly", "lesson", "break", "after"],
    closedMessage: "The bank is closed. Come back tomorrow!",
    opens: "bank",
  },
  tuck_snack: {
    key: "tuck_snack",
    label: "Buy Gala & Fanta",
    emoji: "🥤",
    verb: "snacking",
    durationSec: 5,
    cost: 300,
    effects: { hunger: 25, fun: 5 },
    periods: ["assembly", "break", "after"],
    closedMessage: "The tuck shop is open before assembly, at break and after school.",
    counter: "snacks",
  },
  go_home: {
    key: "go_home",
    label: "Catch the bus home",
    emoji: "🚌",
    verb: "waiting for the bus",
    durationSec: 5,
    cost: 0,
    effects: { energy: 10, fun: 5 },
    periods: ["home"],
    closedMessage: "The school bus leaves at Home Time.",
  },
};

export const jobKeys = Object.values(activities)
  .filter((a) => a.job)
  .map((a) => a.key);

export function getActivity(key: string | null | undefined): ActivityDef | null {
  return (key && activities[key]) || null;
}
