import type { PeriodKind } from "./clock";
import type { SportKind } from "./sports";
import type { WorldKey } from "./worlds";
import { mealActivities } from "./restaurants";
import type { CounterKey, NeedKey } from "./types";

export type ActivityEffects = Partial<Record<NeedKey, number>> & { grades?: number; xp?: number };

/** A part-time job pays when the shift is finished. */
export type JobDef = {
  basePay: number;
  /** Where on the map the job is, for the wallet's "ways to earn" list. */
  where: string;
  /** Extra pay for each classmate at school (customers), up to `maxExtra`. */
  perClassmate?: number;
  maxExtra?: number;
};

export type ActivityDef = {
  key: string;
  label: string;
  /** Shown in a bubble over the student while they do it. */
  emoji: string;
  verb: string;
  durationSec: number;
  /** Price in Naira, paid when the activity starts. */
  cost: number;
  effects: ActivityEffects;
  /** When set, the activity only works during these periods. */
  periods?: PeriodKind[];
  closedMessage?: string;
  counter?: CounterKey;
  job?: JobDef;
  /** Opens a screen (games table, sports, shop, bank) instead of running a timed activity. */
  opens?: "games" | "sports" | "shop" | "bank" | "home" | "furniture" | "food";
  /** For `opens: "sports"`: which sport is played here. */
  sport?: SportKind;
  /** Taking the bus: when the wait is over the student arrives in this world. */
  travelTo?: WorldKey;
  /** Weekly events can make tagged activities cheaper or free. */
  tag?: "market" | "bukka" | "viewing";
  /** Breaking a school rule: a chance of being caught by a prefect, and what it costs. */
  risk?: Risk;
  /** Can only be done this many times a day (counted by `counter`). */
  dailyMax?: number;
  /** Needs a study desk in your room. */
  needsDesk?: boolean;
};

export type Risk = {
  /** 0–1. */
  chance: number;
  caughtText: string;
  fine?: number;
  grades?: number;
  fun?: number;
  /** Seconds stuck in detention. */
  detentionSec?: number;
};

export const activities: Record<string, ActivityDef> = {
  assembly: {
    key: "assembly",
    label: "Join assembly",
    emoji: "🎤",
    verb: "at assembly",
    durationSec: 10,
    cost: 0,
    effects: { social: 8, xp: 10 },
    periods: ["assembly"],
    closedMessage: "Assembly is in the morning.",
    counter: "assembly",
  },
  attend_lesson: {
    key: "attend_lesson",
    label: "Attend lesson",
    emoji: "📝",
    verb: "in class",
    durationSec: 20,
    cost: 0,
    effects: { grades: 12, energy: -6, fun: -3, xp: 15 },
    periods: ["lesson"],
    closedMessage: "No lesson right now — study in the library instead.",
    counter: "lessons",
  },
  study: {
    key: "study",
    label: "Study",
    emoji: "📚",
    verb: "studying",
    durationSec: 15,
    cost: 0,
    effects: { grades: 8, energy: -6, fun: -4, xp: 8 },
    periods: ["assembly", "lesson", "break", "after"],
    closedMessage: "The library is closed. Go home and rest!",
    counter: "study",
  },
  read_comics: {
    key: "read_comics",
    label: "Read comics",
    emoji: "📖",
    verb: "reading",
    durationSec: 10,
    cost: 0,
    effects: { fun: 14, energy: -2 },
    periods: ["assembly", "lesson", "break", "after"],
    closedMessage: "The library is closed.",
  },
  buy_meal: {
    key: "buy_meal",
    label: "Buy jollof rice",
    emoji: "🍛",
    verb: "eating",
    durationSec: 6,
    cost: 500,
    effects: { hunger: 45, fun: 3 },
    periods: ["break", "after"],
    closedMessage: "The canteen opens at break time.",
    counter: "meals",
  },
  buy_snack: {
    key: "buy_snack",
    label: "Buy puff-puff",
    emoji: "🍩",
    verb: "snacking",
    durationSec: 4,
    cost: 200,
    effects: { hunger: 18, fun: 4 },
    periods: ["break", "after"],
    closedMessage: "The canteen opens at break time.",
    counter: "snacks",
  },
  drink_water: {
    key: "drink_water",
    label: "Drink water",
    emoji: "🚰",
    verb: "drinking",
    durationSec: 3,
    cost: 0,
    effects: { hunger: 5, energy: 2 },
  },
  play_football: {
    key: "play_football",
    label: "Play football",
    emoji: "⚽",
    verb: "playing football",
    durationSec: 0,
    cost: 0,
    effects: {},
    periods: ["break", "after"],
    closedMessage: "Sports are for break time and after school.",
    opens: "sports",
    sport: "football",
  },

  rest: {
    key: "rest",
    label: "Rest",
    emoji: "😴",
    verb: "resting",
    durationSec: 12,
    cost: 0,
    effects: { energy: 30 },
    counter: "rest",
  },
  board_games: {
    key: "board_games",
    label: "Play table games",
    emoji: "🎲",
    verb: "playing a table game",
    durationSec: 0,
    cost: 0,
    effects: {},
    periods: ["assembly", "lesson", "break", "after"],
    closedMessage: "The Common Room is closed. See you tomorrow!",
    opens: "games",
  },
  // Part-time jobs: a way to earn money outside lessons. Only a few shifts a day.
  canteen_job: {
    key: "canteen_job",
    label: "Help at the canteen",
    emoji: "🧑‍🍳",
    verb: "serving food",
    durationSec: 15,
    cost: 0,
    effects: { energy: -10, hunger: 10, xp: 5 },
    periods: ["break", "after"],
    closedMessage: "The canteen needs helpers at break and after school.",
    counter: "shifts",
    job: { basePay: 400, where: "Canteen kitchen" },
  },
  library_job: {
    key: "library_job",
    label: "Shelve library books",
    emoji: "📦",
    verb: "shelving books",
    durationSec: 12,
    cost: 0,
    effects: { energy: -6, fun: -4, xp: 5 },
    periods: ["assembly", "break", "after"],
    closedMessage: "The librarian needs help outside lesson time.",
    counter: "shifts",
    job: { basePay: 250, where: "Library, by the bookshelf" },
  },
  sweep_job: {
    key: "sweep_job",
    label: "Sweep the classroom",
    emoji: "🧹",
    verb: "sweeping",
    durationSec: 12,
    cost: 0,
    effects: { energy: -10, fun: -5, xp: 4 },
    periods: ["after"],
    closedMessage: "Classroom cleaning is after school.",
    counter: "shifts",
    job: { basePay: 300, where: "Classroom A, back corner" },
  },
  snack_stall: {
    key: "snack_stall",
    label: "Sell chin-chin",
    emoji: "🛍️",
    verb: "selling chin-chin",
    durationSec: 15,
    cost: 0,
    effects: { energy: -6, social: 6, xp: 6 },
    periods: ["break", "after"],
    closedMessage: "The snack stall opens at break time.",
    counter: "shifts",
    // More classmates at school means more customers.
    job: { basePay: 200, perClassmate: 100, maxExtra: 500, where: "Main Corridor, east end" },
  },
  run_race: {
    key: "run_race",
    label: "Run a race",
    emoji: "🏃",
    verb: "racing",
    durationSec: 0,
    cost: 0,
    effects: {},
    periods: ["break", "after"],
    closedMessage: "Sports are for break time and after school.",
    opens: "sports",
    sport: "race",
  },
  play_tabletennis: {
    key: "play_tabletennis",
    label: "Play table tennis",
    emoji: "🏓",
    verb: "playing table tennis",
    durationSec: 0,
    cost: 0,
    effects: {},
    periods: ["break", "after"],
    closedMessage: "Sports are for break time and after school.",
    opens: "sports",
    sport: "tabletennis",
  },
  play_tenten: {
    key: "play_tenten",
    label: "Play ten-ten",
    emoji: "👣",
    verb: "playing ten-ten",
    durationSec: 0,
    cost: 0,
    effects: {},
    periods: ["assembly", "break", "after"],
    closedMessage: "Ten-ten is for before assembly, break time and after school.",
    opens: "sports",
    sport: "tenten",
  },
  // ---- Breaking the rules (you might get caught) -------------------------
  phone_in_class: {
    key: "phone_in_class",
    label: "Play on your phone in class",
    emoji: "📱",
    verb: "sneakily gaming",
    durationSec: 8,
    cost: 0,
    effects: { fun: 18 },
    periods: ["lesson"],
    closedMessage: "Only works when there's a lesson to be bored in!",
    counter: "mischief",
    risk: { chance: 0.35, caughtText: "📱 A prefect took your phone! Fine ₦300 to get it back.", fine: 300, grades: -5 },
  },
  eat_in_class: {
    key: "eat_in_class",
    label: "Eat snacks in class",
    emoji: "🤫",
    verb: "munching quietly",
    durationSec: 6,
    cost: 0,
    effects: { hunger: 18, fun: 4 },
    periods: ["lesson"],
    closedMessage: "Eating in class only counts during a lesson.",
    counter: "mischief",
    risk: { chance: 0.3, caughtText: "🍪 Caught eating in class — ₦200 fine.", fine: 200 },
  },
  copy_homework: {
    key: "copy_homework",
    label: "Copy someone's homework",
    emoji: "📝",
    verb: "copying homework",
    durationSec: 5,
    cost: 0,
    effects: { grades: 16, xp: 2 },
    periods: ["assembly", "lesson", "break", "after"],
    closedMessage: "The library is closed.",
    counter: "mischief",
    risk: { chance: 0.4, caughtText: "📝 Caught copying! Your work gets a zero.", grades: -20, fun: -10 },
  },
  skip_class: {
    key: "skip_class",
    label: "Skip class behind the shed",
    emoji: "🙈",
    verb: "hiding from class",
    durationSec: 15,
    cost: 0,
    effects: { fun: 20, energy: 12 },
    periods: ["lesson"],
    closedMessage: "There's no class to skip right now.",
    counter: "mischief",
    risk: { chance: 0.3, caughtText: "🙈 A prefect found you skipping class — detention!", detentionSec: 20, grades: -10 },
  },
  // The rest of the school.
  water_crops: {
    key: "water_crops",
    label: "Water the crops",
    emoji: "🪣",
    verb: "watering crops",
    durationSec: 12,
    cost: 0,
    effects: { energy: -10, fun: -2, xp: 4 },
    periods: ["break", "after"],
    closedMessage: "The farm needs helpers at break and after school.",
    counter: "shifts",
    job: { basePay: 300, where: "School Farm" },
  },
  pick_oranges: {
    key: "pick_oranges",
    label: "Pick oranges",
    emoji: "🍊",
    verb: "eating oranges",
    durationSec: 6,
    cost: 0,
    effects: { hunger: 15, fun: 3 },
    periods: ["break", "after"],
    closedMessage: "You can pick oranges at break and after school.",
  },
  watch_match: {
    key: "watch_match",
    label: "Cheer from the stands",
    emoji: "📣",
    verb: "cheering",
    durationSec: 10,
    cost: 0,
    effects: { fun: 10, social: 5 },
    periods: ["break", "after"],
    closedMessage: "Matches are at break and after school.",
  },
  play_basketball: {
    key: "play_basketball",
    label: "Play basketball",
    emoji: "🏀",
    verb: "playing basketball",
    durationSec: 0,
    cost: 0,
    effects: {},
    periods: ["break", "after"],
    closedMessage: "Sports are for break time and after school.",
    opens: "sports",
    sport: "basketball",
  },

  do_experiment: {
    key: "do_experiment",
    label: "Do an experiment",
    emoji: "🧪",
    verb: "doing an experiment",
    durationSec: 15,
    cost: 0,
    effects: { grades: 10, fun: 5, energy: -4, xp: 8 },
    periods: ["lesson", "after"],
    closedMessage: "The lab is open in lesson time and after school.",
    counter: "study",
  },
  practise_coding: {
    key: "practise_coding",
    label: "Practise coding",
    emoji: "💻",
    verb: "coding",
    durationSec: 15,
    cost: 0,
    effects: { grades: 8, fun: 6, energy: -4, xp: 8 },
    periods: ["assembly", "lesson", "break", "after"],
    closedMessage: "The computer lab is closed.",
    counter: "study",
  },
  fix_computers: {
    key: "fix_computers",
    label: "Fix the computers",
    emoji: "🛠️",
    verb: "fixing computers",
    durationSec: 14,
    cost: 0,
    effects: { energy: -8, fun: 2, xp: 6 },
    periods: ["break", "after"],
    closedMessage: "The computer lab needs help at break and after school.",
    counter: "shifts",
    job: { basePay: 350, where: "Computer Lab" },
  },
  play_drums: {
    key: "play_drums",
    label: "Play the drums",
    emoji: "🥁",
    verb: "drumming",
    durationSec: 10,
    cost: 0,
    effects: { fun: 16, social: 3, energy: -4 },
    periods: ["break", "after"],
    closedMessage: "The music room is open at break and after school.",
  },
  paint: {
    key: "paint",
    label: "Paint a picture",
    emoji: "🎨",
    verb: "painting",
    durationSec: 12,
    cost: 0,
    effects: { fun: 14, energy: -2, xp: 3 },
    periods: ["break", "after"],
    closedMessage: "The art room is open at break and after school.",
  },
  watch_tv: {
    key: "watch_tv",
    label: "Watch TV",
    emoji: "📺",
    verb: "watching TV",
    durationSec: 12,
    cost: 0,
    effects: { fun: 14, energy: 4 },
    periods: ["break", "after"],
    closedMessage: "The TV is on at break and after school.",
  },
  listen_music: {
    key: "listen_music",
    label: "Listen to music",
    emoji: "🎧",
    verb: "listening to music",
    durationSec: 8,
    cost: 0,
    effects: { fun: 10, social: 2 },
    periods: ["break", "after"],
    closedMessage: "The music corner is open at break and after school.",
  },
  rest_sickbay: {
    key: "rest_sickbay",
    label: "Lie down in the sick bay",
    emoji: "🛏️",
    verb: "resting in the sick bay",
    durationSec: 18,
    cost: 0,
    effects: { energy: 45 },
    counter: "rest",
  },
  school_shop: {
    key: "school_shop",
    label: "Shop for clothes",
    emoji: "🛍️",
    verb: "shopping",
    durationSec: 0,
    cost: 0,
    effects: {},
    periods: ["assembly", "lesson", "break", "after"],
    closedMessage: "The shop is closed. Come back tomorrow!",
    opens: "shop",
  },
  school_bank: {
    key: "school_bank",
    label: "Use the School Bank",
    emoji: "🏦",
    verb: "at the bank",
    durationSec: 0,
    cost: 0,
    effects: {},
    periods: ["assembly", "lesson", "break", "after"],
    closedMessage: "The bank is closed. Come back tomorrow!",
    opens: "bank",
  },
  tuck_snack: {
    key: "tuck_snack",
    label: "Buy Gala & Fanta",
    emoji: "🥤",
    verb: "snacking",
    durationSec: 5,
    cost: 300,
    effects: { hunger: 25, fun: 5 },
    periods: ["assembly", "break", "after"],
    closedMessage: "The tuck shop is open before assembly, at break and after school.",
    counter: "snacks",
  },
  bus_to_town: {
    key: "bus_to_town",
    label: "Catch the bus to town",
    emoji: "🚌",
    verb: "waiting for the bus",
    durationSec: 4,
    cost: 0,
    effects: {},
    travelTo: "town",
  },
  // ---- Town --------------------------------------------------------------
  bus_to_school: {
    key: "bus_to_school",
    label: "Catch the bus to school",
    emoji: "🚌",
    verb: "waiting for the bus",
    durationSec: 4,
    cost: 0,
    effects: {},
    travelTo: "school",
  },
  my_room: {
    key: "my_room",
    label: "Go to your room",
    emoji: "🏠",
    verb: "at home",
    durationSec: 0,
    cost: 0,
    effects: {},
    opens: "home",
  },
  sleep_home: {
    key: "sleep_home",
    label: "Sleep in your bed",
    emoji: "😴",
    verb: "sleeping",
    durationSec: 18,
    cost: 0,
    effects: { energy: 50 },
    counter: "rest",
  },
  study_home: {
    key: "study_home",
    label: "Study at your desk",
    emoji: "📖",
    verb: "studying at home",
    durationSec: 12,
    cost: 0,
    effects: { grades: 6, xp: 8, energy: -5, fun: -3 },
    counter: "homeStudy",
    dailyMax: 3,
    needsDesk: true,
  },
  salon_look: {
    key: "salon_look",
    label: "Get a new look",
    emoji: "💇",
    verb: "at the salon",
    durationSec: 0,
    cost: 0,
    effects: {},
    opens: "shop",
  },
  salon_job: {
    key: "salon_job",
    label: "Sweep the salon",
    emoji: "🧹",
    verb: "sweeping the salon",
    durationSec: 12,
    cost: 0,
    effects: { energy: -8, fun: -2, xp: 4 },
    counter: "shifts",
    job: { basePay: 250, where: "Barber & Salon, in town" },
  },
  supermarket_snack: {
    key: "supermarket_snack",
    label: "Buy biscuits & a drink",
    emoji: "🛒",
    verb: "snacking",
    durationSec: 5,
    cost: 250,
    effects: { hunger: 25, fun: 4 },
    counter: "snacks",
  },
  furniture_shop: {
    key: "furniture_shop",
    label: "Shop for furniture",
    emoji: "🛋️",
    verb: "shopping",
    durationSec: 0,
    cost: 0,
    effects: {},
    opens: "furniture",
  },
  viewing_match: {
    key: "viewing_match",
    label: "Watch the match",
    emoji: "📺",
    verb: "watching the match",
    durationSec: 15,
    cost: 100,
    effects: { fun: 22, social: 6 },
    tag: "viewing",
  },
  mama_put: {
    key: "mama_put",
    label: "Eat at Mama Put",
    emoji: "🍲",
    verb: "eating",
    durationSec: 6,
    cost: 350,
    effects: { hunger: 42, fun: 3 },
    counter: "meals",
    tag: "market",
  },
  buy_fruit: {
    key: "buy_fruit",
    label: "Buy fruit",
    emoji: "🍌",
    verb: "eating fruit",
    durationSec: 4,
    cost: 150,
    effects: { hunger: 15, fun: 4 },
    counter: "snacks",
    tag: "market",
  },
  market_stall: {
    key: "market_stall",
    label: "Sell at the market",
    emoji: "🧺",
    verb: "selling at the market",
    durationSec: 15,
    cost: 0,
    effects: { energy: -8, social: 6, xp: 6 },
    counter: "shifts",
    job: { basePay: 300, perClassmate: 100, maxExtra: 400, where: "Market, in town" },
  },
  food_court: {
    key: "food_court",
    label: "Order food",
    emoji: "🍽️",
    verb: "ordering",
    durationSec: 0,
    cost: 0,
    effects: {},
    opens: "food",
  },
  eat_together: {
    key: "eat_together",
    label: "Share a big plate at Mama's Bukka",
    emoji: "🍛",
    verb: "eating at the bukka",
    durationSec: 10,
    cost: 600,
    effects: { hunger: 50, social: 12, fun: 5 },
    counter: "meals",
    tag: "bukka",
  },
  park_football: {
    key: "park_football",
    label: "Play football",
    emoji: "⚽",
    verb: "playing football",
    durationSec: 0,
    cost: 0,
    effects: {},
    opens: "sports",
    sport: "football",
  },
  relax_square: {
    key: "relax_square",
    label: "Relax in the square",
    emoji: "🕊️",
    verb: "relaxing",
    durationSec: 10,
    cost: 0,
    effects: { energy: 15, fun: 6, social: 3 },
  },

};

// Every dish at the Food Court.
Object.assign(activities, mealActivities());

export const jobKeys = Object.values(activities)
  .filter((a) => a.job)
  .map((a) => a.key);

export function getActivity(key: string | null | undefined): ActivityDef | null {
  return (key && activities[key]) || null;
}
